--------------------------------------------------------
--  File created - Wednesday-December-07-2016   
--------------------------------------------------------
REM INSERTING into MOVIE
SET DEFINE OFF;
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (1,'Your Name','Makoto Shinkai','Kimi no Na wa. revolves around Mitsuha and Taki''s actions, which begin to have a dramatic impact on each other''s lives, weaving them into a fabric held together by fate and circumstance.',106,0,'false',to_date('01-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (2,'The Warriors Gate','Matthias Hoene','A teenager is magically transported to China and learns to convert his video game skills into those of a Kung Fu warrior.',107,0,'false',to_date('01-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (3,'Disappointments Room','D.J. Caruso','The Disappointments Room ผลงานการเขียนบทของ เวนธ์เวิร์ธ มิลเลอร์ (Prison Break) นำแสดงโดย เคท เบคคินเซล รับบท ดาน่า เธอและครอบครัวที่ย้ายเข้ามาในบ้านในฝัน แต่ความสยองขวัญขั้นสุดก็เกิดขึ้นเมื่อเธอบังเอิญปลดล็อคประตูห้องลับใต้หลังคา ปลดปล่อยบางอย่างที่น่ากลัวเกินกว่าจินตนาการ',92,0,'false',to_date('01-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (4,'Billy Lynn Long Halftime Walk','Ang Lee','19-year-old Billy Lynn is brought home for a victory tour after a harrowing Iraq battle. Through flashbacks the film shows what really happened to his squad - contrasting the realities of war with America''s perceptions.',113,0,'false',to_date('01-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (5,'Trolls','Mike Mitchell, Walt Dohrn','After the Bergens invade Troll Village, Poppy, the happiest Troll ever born, and the curmudgeonly Branch set off on a journey to rescue her friends.',92,0,'false',to_date('08-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (6,'Nocturnal Animals','Tom Ford','An art gallery owner is haunted by her ex-husband''s novel, a violent thriller she interprets as a veiled threat and a symbolic revenge tale.',116,0,'false',to_date('08-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (7,'Moana','Ron Clements, John Musker','In Ancient Polynesia, when a terrible curse incurred by Maui reaches an impetuous Chieftain''s daughter''s island, she answers the Ocean''s call to seek out the demigod to set things right.',113,0,'false',to_date('08-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (8,'A Monster Calls','J.A. Bayona','A boy seeks the help of a tree monster to cope with his single mom''s terminal illness.',109,0,'false',to_date('08-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (9,'Fantastic Beasts','David Yates','The adventures of writer Newt Scamander in New York''s secret community of witches and wizards seventy years before Harry Potter reads his book in school.',132,0,'true',to_date('15-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (10,'Bleed for This','Ben Younger','The inspirational story of World Champion Boxer Vinny Pazienza, who after a near fatal car crash, which left him not knowing if he''d ever walk again, made one of sports most incredible comebacks.',117,0,'true',to_date('15-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (11,'Miss Saigon','Claude-Michel Schönberg, Alain Boublil','The musical''s inspiration was reportedly a photograph, which Schönberg found inadvertently in a magazine. The photograph showed a Vietnamese mother leaving her child at a departure gate at Tan Son Nhut Air Base to board an airplane headed for the United States where her father, an ex-GI, would be in a position to provide a much better life for the child. Schönberg considered this mother''s actions for her child to be "The Ultimate Sacrifice," an idea central to the plot of Miss Saigon',187,0,'true',to_date('15-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (12,'Underworld 5','Anna Foerster','Vampire death dealer, Selene (Kate Beckinsale) fights to end the eternal war between the Lycan clan and the Vampire faction that betrayed her.',91,0,'true',to_date('15-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (13,'OFFICE CHRISTMAS PARTY','Josh Gordon, Will Speck','When his uptight CEO sister threatens to shut down his branch, the branch manager throws an epic Christmas party in order to land a big client and save the day, but the party gets way out of hand...',105,0,'false',to_date('22-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
Insert into MOVIE (MOVIEID,MOVIENAME,DIRECTOR,SHORTDESCRIPTION,DURATION,PLAYCOUNT,STATUS,SHOWDATE) values (14,'Rogue One','Gareth Edwards','The Rebellion makes a risky move to steal the plans to the Death Star, setting up the epic saga to follow.',133,0,'false',to_date('22-DEC-16 00:00:00','DD-MON-RR HH24:MI:SS'));
