--------------------------------------------------------
--  File created - วันพุธ-ธันวาคม-07-2559   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACTOR
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."ACTOR" 
   (	"ACTORID" NUMBER(10,0), 
	"ACTORNAME" VARCHAR2(70 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."CATEGORY" 
   (	"CATEGORYID" NUMBER(10,0), 
	"CATEGORYNAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."EMPLOYEE" 
   (	"EMPID" NUMBER(10,0), 
	"JOBPOSITION" VARCHAR2(20 BYTE) DEFAULT 'Staff', 
	"SALARY" NUMBER(10,0) DEFAULT 0, 
	"CITIZENID" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOOD
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."FOOD" 
   (	"FOODID" NUMBER(10,0), 
	"NAME" VARCHAR2(35 BYTE), 
	"TYPE" VARCHAR2(35 BYTE), 
	"PRICE" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."MEMBER" 
   (	"MEMBERID" NUMBER(10,0), 
	"STARTDATE" DATE, 
	"EXPIRYDATE" DATE, 
	"CITIZENID" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MOVIE
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."MOVIE" 
   (	"MOVIEID" NUMBER(10,0), 
	"MOVIENAME" VARCHAR2(70 BYTE), 
	"DIRECTOR" VARCHAR2(70 BYTE), 
	"SHORTDESCRIPTION" VARCHAR2(4000 BYTE), 
	"DURATION" NUMBER(4,0), 
	"PLAYCOUNT" NUMBER(10,0) DEFAULT 0, 
	"STATUS" VARCHAR2(20 BYTE), 
	"SHOWDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MOVIE_ACTOR
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."MOVIE_ACTOR" 
   (	"MOVIEID" NUMBER(10,0), 
	"ACTORID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MOVIE_CATEGORY
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."MOVIE_CATEGORY" 
   (	"MOVIEID" NUMBER(10,0), 
	"CATEGORYID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."PERSON" 
   (	"CITIZENID" VARCHAR2(13 BYTE), 
	"FNAME" VARCHAR2(35 BYTE), 
	"LNAME" VARCHAR2(35 BYTE), 
	"GENDER" CHAR(1 BYTE), 
	"BIRTHDATE" DATE, 
	"ADDRESS" VARCHAR2(95 BYTE), 
	"EMAIL" VARCHAR2(62 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."REVIEW" 
   (	"MOVIEID" NUMBER(10,0), 
	"MEMBERID" NUMBER(10,0), 
	"RATING" NUMBER(2,0) DEFAULT 0, 
	"COMMENTS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SEAT
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."SEAT" 
   (	"SEATROW" VARCHAR2(1 BYTE), 
	"SEATNUMBER" NUMBER(4,0), 
	"ZONE" VARCHAR2(20 BYTE) DEFAULT 'General', 
	"THEATREID" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SELL
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."SELL" 
   (	"FOODID" NUMBER(10,0), 
	"EMPID" NUMBER(10,0), 
	"SDATE" DATE, 
	"AMOUNT" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SHOWTIME
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."SHOWTIME" 
   (	"SHOWDATE" DATE, 
	"MOVIEID" NUMBER(10,0), 
	"THEATREID" NUMBER(2,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table THEATRE
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."THEATRE" 
   (	"THEATREID" NUMBER(2,0), 
	"SEATCAPACITY" NUMBER(3,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "WATCHANAN"."TICKET" 
   (	"TICKETID" NUMBER(10,0), 
	"MEMBERID" NUMBER(10,0), 
	"SEATROW" VARCHAR2(1 BYTE), 
	"SEATNUMBER" NUMBER(4,0), 
	"THEATREID" NUMBER(2,0), 
	"SHOWDATE" DATE, 
	"MOVIEID" NUMBER(10,0), 
	"EMPID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence ACTOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WATCHANAN"."ACTOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CATEGORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WATCHANAN"."CATEGORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYEE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WATCHANAN"."EMPLOYEE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOOD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WATCHANAN"."FOOD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEMBER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WATCHANAN"."MEMBER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MOVIE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WATCHANAN"."MOVIE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TICKET_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WATCHANAN"."TICKET_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into WATCHANAN.ACTOR
SET DEFINE OFF;
REM INSERTING into WATCHANAN.CATEGORY
SET DEFINE OFF;
REM INSERTING into WATCHANAN.EMPLOYEE
SET DEFINE OFF;
REM INSERTING into WATCHANAN.FOOD
SET DEFINE OFF;
REM INSERTING into WATCHANAN.MEMBER
SET DEFINE OFF;
REM INSERTING into WATCHANAN.MOVIE
SET DEFINE OFF;
REM INSERTING into WATCHANAN.MOVIE_ACTOR
SET DEFINE OFF;
REM INSERTING into WATCHANAN.MOVIE_CATEGORY
SET DEFINE OFF;
REM INSERTING into WATCHANAN.PERSON
SET DEFINE OFF;
REM INSERTING into WATCHANAN.REVIEW
SET DEFINE OFF;
REM INSERTING into WATCHANAN.SEAT
SET DEFINE OFF;
REM INSERTING into WATCHANAN.SELL
SET DEFINE OFF;
REM INSERTING into WATCHANAN.SHOWTIME
SET DEFINE OFF;
REM INSERTING into WATCHANAN.THEATRE
SET DEFINE OFF;
REM INSERTING into WATCHANAN.TICKET
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ACTOR_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."ACTOR_PK1" ON "WATCHANAN"."ACTOR" ("ACTORID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MOVIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."MOVIE_PK" ON "WATCHANAN"."MOVIE" ("MOVIEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSON_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."PERSON_UK2" ON "WATCHANAN"."PERSON" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."EMPLOYEE_PK" ON "WATCHANAN"."EMPLOYEE" ("EMPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."ACTOR_PK" ON "WATCHANAN"."ACTOR" ("ACTORID", "ACTORNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SELL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."SELL_PK" ON "WATCHANAN"."SELL" ("FOODID", "EMPID", "SDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SHOWTIME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."SHOWTIME_PK" ON "WATCHANAN"."SHOWTIME" ("SHOWDATE", "MOVIEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."CATEGORY_PK" ON "WATCHANAN"."CATEGORY" ("CATEGORYID", "CATEGORYNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATEGORY_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."CATEGORY_PK1" ON "WATCHANAN"."CATEGORY" ("CATEGORYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."PERSON_PK" ON "WATCHANAN"."PERSON" ("CITIZENID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOOD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."FOOD_PK" ON "WATCHANAN"."FOOD" ("FOODID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MOVIE_CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."MOVIE_CATEGORY_PK" ON "WATCHANAN"."MOVIE_CATEGORY" ("MOVIEID", "CATEGORYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSON_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."PERSON_UK1" ON "WATCHANAN"."PERSON" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index THEATRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."THEATRE_PK" ON "WATCHANAN"."THEATRE" ("THEATREID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."TICKET_PK" ON "WATCHANAN"."TICKET" ("TICKETID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."MEMBER_PK" ON "WATCHANAN"."MEMBER" ("MEMBERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REVIEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."REVIEW_PK" ON "WATCHANAN"."REVIEW" ("MOVIEID", "MEMBERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MOVIE_ACTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."MOVIE_ACTOR_PK" ON "WATCHANAN"."MOVIE_ACTOR" ("MOVIEID", "ACTORID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SEAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WATCHANAN"."SEAT_PK" ON "WATCHANAN"."SEAT" ("SEATROW", "SEATNUMBER", "THEATREID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ACTOR_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WATCHANAN"."ACTOR_TRG" 
BEFORE INSERT ON ACTOR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT ACTOR_SEQ.NEXTVAL INTO :NEW.ACTORID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WATCHANAN"."ACTOR_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATEGORY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WATCHANAN"."CATEGORY_TRG" 
BEFORE INSERT ON CATEGORY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT CATEGORY_SEQ.NEXTVAL INTO :NEW.CATEGORYID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WATCHANAN"."CATEGORY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYEE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WATCHANAN"."EMPLOYEE_TRG" 
BEFORE INSERT ON EMPLOYEE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT EMPLOYEE_SEQ.NEXTVAL INTO :NEW.EMPID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WATCHANAN"."EMPLOYEE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FOOD_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WATCHANAN"."FOOD_TRG" 
BEFORE INSERT ON FOOD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT FOOD_SEQ.NEXTVAL INTO :NEW.FOODID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WATCHANAN"."FOOD_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MEMBER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WATCHANAN"."MEMBER_TRG" 
BEFORE INSERT ON MEMBER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT MEMBER_SEQ.NEXTVAL INTO :NEW.MEMBERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WATCHANAN"."MEMBER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MOVIE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WATCHANAN"."MOVIE_TRG" 
BEFORE INSERT ON MOVIE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT MOVIE_SEQ.NEXTVAL INTO :NEW.MOVIEID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WATCHANAN"."MOVIE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TICKET_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WATCHANAN"."TICKET_TRG" 
BEFORE INSERT ON TICKET 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT TICKET_SEQ.NEXTVAL INTO :NEW.TICKETID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WATCHANAN"."TICKET_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table SEAT
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."SEAT" MODIFY ("SEATROW" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."SEAT" MODIFY ("SEATNUMBER" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."SEAT" MODIFY ("ZONE" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."SEAT" MODIFY ("THEATREID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."SEAT" ADD CONSTRAINT "SEAT_PK" PRIMARY KEY ("SEATROW", "SEATNUMBER", "THEATREID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."PERSON" MODIFY ("CITIZENID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."PERSON" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."PERSON" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."PERSON" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."PERSON" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."PERSON" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."PERSON" ADD CONSTRAINT "PERSON_PK" PRIMARY KEY ("CITIZENID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WATCHANAN"."PERSON" ADD CONSTRAINT "PERSON_UK1" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WATCHANAN"."PERSON" ADD CONSTRAINT "PERSON_UK2" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOOD
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."FOOD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."FOOD" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."FOOD" ADD CONSTRAINT "FOOD_PK" PRIMARY KEY ("FOODID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACTOR
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."ACTOR" MODIFY ("ACTORID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."ACTOR" MODIFY ("ACTORNAME" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."ACTOR" ADD CONSTRAINT "ACTOR_PK" PRIMARY KEY ("ACTORID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MOVIE_CATEGORY
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."MOVIE_CATEGORY" ADD CONSTRAINT "MOVIE_CATEGORY_PK" PRIMARY KEY ("MOVIEID", "CATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WATCHANAN"."MOVIE_CATEGORY" MODIFY ("CATEGORYID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."MOVIE_CATEGORY" MODIFY ("MOVIEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."CATEGORY" MODIFY ("CATEGORYID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."CATEGORY" MODIFY ("CATEGORYNAME" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."CATEGORY" ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."TICKET" MODIFY ("MEMBERID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."TICKET" MODIFY ("SEATROW" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."TICKET" MODIFY ("SEATNUMBER" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."TICKET" MODIFY ("THEATREID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."TICKET" MODIFY ("SHOWDATE" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."TICKET" MODIFY ("MOVIEID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."TICKET" MODIFY ("EMPID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."TICKET" ADD CONSTRAINT "TICKET_PK" PRIMARY KEY ("TICKETID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MOVIE_ACTOR
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."MOVIE_ACTOR" ADD CONSTRAINT "MOVIE_ACTOR_PK" PRIMARY KEY ("MOVIEID", "ACTORID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WATCHANAN"."MOVIE_ACTOR" MODIFY ("ACTORID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."MOVIE_ACTOR" MODIFY ("MOVIEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SELL
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."SELL" ADD CONSTRAINT "SELL_PK" PRIMARY KEY ("FOODID", "EMPID", "SDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WATCHANAN"."SELL" MODIFY ("FOODID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."SELL" MODIFY ("EMPID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."SELL" MODIFY ("SDATE" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."SELL" MODIFY ("AMOUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."REVIEW" MODIFY ("MOVIEID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."REVIEW" MODIFY ("MEMBERID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."REVIEW" ADD CONSTRAINT "REVIEW_PK" PRIMARY KEY ("MOVIEID", "MEMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WATCHANAN"."REVIEW" ADD CONSTRAINT "REVIEW_CHK1" CHECK (rating >= 0 and rating <= 5) ENABLE;
--------------------------------------------------------
--  Constraints for Table MOVIE
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."MOVIE" MODIFY ("SHOWDATE" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."MOVIE" ADD CONSTRAINT "MOVIE_PK" PRIMARY KEY ("MOVIEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."MEMBER" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."MEMBER" MODIFY ("EXPIRYDATE" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."MEMBER" MODIFY ("CITIZENID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("MEMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table THEATRE
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."THEATRE" MODIFY ("THEATREID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."THEATRE" MODIFY ("SEATCAPACITY" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."THEATRE" ADD CONSTRAINT "THEATRE_PK" PRIMARY KEY ("THEATREID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SHOWTIME
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."SHOWTIME" MODIFY ("SHOWDATE" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."SHOWTIME" MODIFY ("MOVIEID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."SHOWTIME" MODIFY ("THEATREID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."SHOWTIME" ADD CONSTRAINT "SHOWTIME_PK" PRIMARY KEY ("SHOWDATE", "MOVIEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."EMPLOYEE" MODIFY ("JOBPOSITION" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."EMPLOYEE" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."EMPLOYEE" MODIFY ("CITIZENID" NOT NULL ENABLE);
  ALTER TABLE "WATCHANAN"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FK1" FOREIGN KEY ("CITIZENID")
	  REFERENCES "WATCHANAN"."PERSON" ("CITIZENID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."MEMBER" ADD CONSTRAINT "MEMBER_FK1" FOREIGN KEY ("CITIZENID")
	  REFERENCES "WATCHANAN"."PERSON" ("CITIZENID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOVIE_ACTOR
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."MOVIE_ACTOR" ADD CONSTRAINT "MOVIE_ACTOR_FK1" FOREIGN KEY ("MOVIEID")
	  REFERENCES "WATCHANAN"."MOVIE" ("MOVIEID") ENABLE;
  ALTER TABLE "WATCHANAN"."MOVIE_ACTOR" ADD CONSTRAINT "MOVIE_ACTOR_FK2" FOREIGN KEY ("ACTORID")
	  REFERENCES "WATCHANAN"."ACTOR" ("ACTORID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOVIE_CATEGORY
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."MOVIE_CATEGORY" ADD CONSTRAINT "MOVIE_CATEGORY_FK1" FOREIGN KEY ("MOVIEID")
	  REFERENCES "WATCHANAN"."MOVIE" ("MOVIEID") ENABLE;
  ALTER TABLE "WATCHANAN"."MOVIE_CATEGORY" ADD CONSTRAINT "MOVIE_CATEGORY_FK2" FOREIGN KEY ("CATEGORYID")
	  REFERENCES "WATCHANAN"."CATEGORY" ("CATEGORYID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."REVIEW" ADD CONSTRAINT "REVIEW_FK1" FOREIGN KEY ("MEMBERID")
	  REFERENCES "WATCHANAN"."MEMBER" ("MEMBERID") ENABLE;
  ALTER TABLE "WATCHANAN"."REVIEW" ADD CONSTRAINT "REVIEW_FK2" FOREIGN KEY ("MOVIEID")
	  REFERENCES "WATCHANAN"."MOVIE" ("MOVIEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEAT
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."SEAT" ADD CONSTRAINT "SEAT_FK1" FOREIGN KEY ("THEATREID")
	  REFERENCES "WATCHANAN"."THEATRE" ("THEATREID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SELL
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."SELL" ADD CONSTRAINT "SELL_FK1" FOREIGN KEY ("FOODID")
	  REFERENCES "WATCHANAN"."FOOD" ("FOODID") ENABLE;
  ALTER TABLE "WATCHANAN"."SELL" ADD CONSTRAINT "SELL_FK2" FOREIGN KEY ("EMPID")
	  REFERENCES "WATCHANAN"."EMPLOYEE" ("EMPID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SHOWTIME
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."SHOWTIME" ADD CONSTRAINT "SHOWTIME_FK1" FOREIGN KEY ("THEATREID")
	  REFERENCES "WATCHANAN"."THEATRE" ("THEATREID") ENABLE;
  ALTER TABLE "WATCHANAN"."SHOWTIME" ADD CONSTRAINT "SHOWTIME_FK2" FOREIGN KEY ("MOVIEID")
	  REFERENCES "WATCHANAN"."MOVIE" ("MOVIEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "WATCHANAN"."TICKET" ADD CONSTRAINT "TICKET_FK1" FOREIGN KEY ("MEMBERID")
	  REFERENCES "WATCHANAN"."MEMBER" ("MEMBERID") ENABLE;
  ALTER TABLE "WATCHANAN"."TICKET" ADD CONSTRAINT "TICKET_FK2" FOREIGN KEY ("SEATROW", "SEATNUMBER", "THEATREID")
	  REFERENCES "WATCHANAN"."SEAT" ("SEATROW", "SEATNUMBER", "THEATREID") ENABLE;
  ALTER TABLE "WATCHANAN"."TICKET" ADD CONSTRAINT "TICKET_FK3" FOREIGN KEY ("SHOWDATE", "MOVIEID")
	  REFERENCES "WATCHANAN"."SHOWTIME" ("SHOWDATE", "MOVIEID") ENABLE;
  ALTER TABLE "WATCHANAN"."TICKET" ADD CONSTRAINT "TICKET_FK4" FOREIGN KEY ("EMPID")
	  REFERENCES "WATCHANAN"."EMPLOYEE" ("EMPID") ENABLE;
