//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nok_cinema_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW
    {
        public int MOVIEID { get; set; }
        public int MEMBERID { get; set; }
        public Nullable<byte> RATING { get; set; }
        public string COMMENTS { get; set; }
    
        public virtual MEMBER MEMBER { get; set; }
    }
}
