//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nok_cinema_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELL
    {
        public int FOODID { get; set; }
        public int EMPID { get; set; }
        public System.DateTime SDATE { get; set; }
        public int AMOUNT { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual FOOD FOOD { get; set; }
    }
}
