//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nok_cinema_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        public int TICKETID { get; set; }
        public int MEMBERID { get; set; }
        public string SEATROW { get; set; }
        public string SEATNUMBER { get; set; }
        public byte THEATREID { get; set; }
        public System.DateTime SHOWDATE { get; set; }
        public int MOVIEID { get; set; }
        public int EMPID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual MEMBER MEMBER { get; set; }
        public virtual SEAT SEAT { get; set; }
        public virtual SHOWTIME SHOWTIME { get; set; }
    }
}
